Product:
    type: object
    config:
        description: "Product Type"
        fields:
            id:
              type: "Int"
              description: "Product Id"
            name:
                type: "String"
                description: "Product name"
            price:
                type:  "Float"
                description: "Product Price"
            description:
                type: "String"
                description: "Product Description"
            Slug:
                type: "String"
                description: "Product Slug" 